export const FALLBACK_COURSES = [
  {
    id: "c1",
    title: "Maîtriser la fenêtre de vent",
    sport: "kitesurf",
    level: "Débutant",
    duration: "12 min",
    thumbnail: "https://images.unsplash.com/photo-1627068477565-3a66d5f76d5e?w=800",
    description: "Comprendre où placer ton kite et comment lire la fenêtre de vent.",
    coming_soon: true,
  },
  {
    id: "c2",
    title: "Le water start parfait",
    sport: "kitesurf",
    level: "Débutant",
    duration: "18 min",
    thumbnail: "https://images.unsplash.com/photo-1578060124065-41f863eb9ebe?w=800",
    description: "Décolle proprement de l'eau à chaque essai.",
    coming_soon: true,
  },
  {
    id: "c3",
    title: "Premier saut & pop",
    sport: "kitesurf",
    level: "Intermédiaire",
    duration: "22 min",
    thumbnail: "https://images.unsplash.com/photo-1667323567346-ea4048f36c58?fm=jpg&q=85&w=800&auto=format&fit=crop",
    description: "Construis ton premier saut: edge, send, pop, réception.",
    coming_soon: true,
  },
  {
    id: "c4",
    title: "Backroll & rotations",
    sport: "kitesurf",
    level: "Avancé",
    duration: "26 min",
    thumbnail: "https://images.unsplash.com/photo-1632990848833-2e7007adb204?w=800",
    description: "Décompose le backroll étape par étape avec drills.",
    coming_soon: true,
  },
  {
    id: "c5",
    title: "Initiation au foil",
    sport: "foil",
    level: "Débutant",
    duration: "20 min",
    thumbnail: "https://images.unsplash.com/photo-1777897161531-5fdeec1e9a4c?fm=jpg&q=85&w=800&auto=format&fit=crop",
    description: "Apprends à voler stable sur ton foil.",
    coming_soon: true,
  },
  {
    id: "c6",
    title: "Pop wakeboard derrière bateau",
    sport: "wakeboard",
    level: "Intermédiaire",
    duration: "16 min",
    thumbnail: "https://images.unsplash.com/photo-1666032234128-abc3e45bd1dc?fm=jpg&q=85&w=800&auto=format&fit=crop",
    description: "Edge agressif et pop explosif au wake.",
    coming_soon: true,
  },
];
